I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 68, in script
    valetina "just take it"
Exception: Sayer 'valetina' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 68, in script
    valetina "just take it"
  File "D:\renpy\renpy-7.3.5-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\renpy\renpy-7.3.5-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'valetina' is not defined.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
ptagain 1.0
Thu Sep 29 21:51:19 2022
