I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 177, in script
    show mayday deep with dissolve
Exception: Image 'mayday' does not accept attributes 'deep'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 177, in script
    show mayday deep with dissolve
  File "/home/cpu/renpy8/renpy/ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/home/cpu/renpy8/renpy/ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "/home/cpu/renpy8/renpy/exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "/home/cpu/renpy8/renpy/display/image.py", line 413, in find_target
    self.target = target._duplicate(a)
  File "/home/cpu/renpy8/renpy/display/core.py", line 397, in _duplicate
    args.extraneous()
  File "/home/cpu/renpy8/renpy/display/core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'mayday' does not accept attributes 'deep'.

Linux-5.19.9-arch1-1-x86_64-with-glibc2.36 x86_64
Ren'Py 8.0.1.22070801
ptagain 1.0
Sat Oct  1 18:50:13 2022
